CREATE TABLE CRI_CRIANCA(
	CRI_ID							INT(13) 		NOT NULL,
	CRI_NOME						VARCHAR(80) 	NOT NULL,
	CRI_PAI							VARCHAR(80) 	NOT NULL,
	CRI_MAE							VARCHAR(80) 	NOT NULL,
	CRI_NASCIMENTO 					DATE			NOT NULL,
	CRI_MOTIVO						VARCHAR(80)		NOT NULL,
	CRI_TELEFONE					LONG			NOT NULL,
	CRI_SEXO						VARCHAR(1)		NOT NULL,
	CONSTRAINT CRI_PK 				PRIMARY KEY (CRI_ID)
	);
	
CREATE UNIQUE INDEX CRI_INDEX ON CRI_CRIANCA(CRI_ID);

	
CREATE TABLE CLI_CLINICO(
	CLI_ID							INT(13)			NOT NULL,
	CLI_DOENCA						VARCHAR(30)		NOT NULL,
	CONSTRAINT CLI_PK				PRIMARY KEY (CLI_ID),
	CONSTRAINT CLI_UK				UNIQUE (CLI_DOENCA)
	);
	
CREATE UNIQUE INDEX CLI_INDEX ON CLI_CLINICO(CLI_ID);
	
	
CREATE TABLE CLINICO_CRIANCA(
	CRI_ID							INT(13)			NOT NULL,
	CLI_ID							INT(13)			NOT NULL,
	CONSTRAINT CLI_CRI_PK			PRIMARY KEY (CRI_ID, CLI_ID),
	CONSTRAINT CLI_CRI_FK			FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID),
	CONSTRAINT CLI_CRI_FK2			FOREIGN KEY (CLI_ID) REFERENCES CLI_CLINICO (CLI_ID)
	);

CREATE UNIQUE INDEX CRI_CLI_INDEX ON CLINICO_CRIANCA(CRI_ID,CLI_ID);

	
CREATE TABLE ANT_ANTROPOMETRICO(
	ANT_ID							INT(13)			NOT NULL,
	ANT_PESO_HABITUAL				DOUBLE(5,2)		NOT NULL,
	ANT_PESO_ATUAL					DOUBLE(5,2)		NOT NULL,
	ANT_PESO_ESTIMADO				DOUBLE(5,2)		NOT NULL,
	ANT_ESTATURA					DOUBLE(5,2)		NOT NULL,
	ANT_PERIMETRO_CRANIANO  		DOUBLE(5,2)		NOT NULL,
	ANT_PERIMETRO_TORACICO			DOUBLE(5,2)		NOT NULL,
	ANT_ALTERACAO_PESO_RECENTE		DOUBLE(5,2)		NOT NULL,
	ANT_CIRCUNFERENCIA_ABDOMINAL	DOUBLE(5,2)		NOT NULL,
	ANT_CIRCUNFERENCIA_COXA			DOUBLE(5,2)		NOT NULL,
	ANT_CIRCUNFERENCIA_PANTURRILHA	DOUBLE(5,2)		NOT NULL,
	ANT_CIRCUNFERENCIA_PESCOCO		DOUBLE(5,2)		NOT NULL,
	ANT_DOBRA_CUTANEA_TRICIPITAL	DOUBLE(5,2)		NOT NULL,
	ANT_DOBRA_CUTANEA_SUBESCALAR	DOUBLE(5,2)		NOT NULL,
	ANT_DOBRA_CUTANEA_BICIBITAL		DOUBLE(5,2)		NOT NULL,
	ANT_DOBRA_CUTANEA_SUPRA_ILIACA	DOUBLE(5,2)		NOT NULL,
	ANT_AREA_MUSCULAR_POLEGAR		DOUBLE(5,2)		NOT NULL,
	ANT_DATA						DATE			NOT NULL,
	CRI_ID							INT(13)			NOT NULL,
	CONSTRAINT ANT_PK 				PRIMARY KEY (ANT_ID),
	CONSTRAINT ANT_FK				FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE UNIQUE INDEX ANT_INDEX ON ANT_ANTROPOMETRICO(CRI_ID);

	
CREATE TABLE REM_REMEDIO(
	REM_ID							INT(13) 		NOT NULL,
	REM_NOME						VARCHAR(30)		NOT NULL,
	CONSTRAINT REM_PK				PRIMARY KEY (REM_ID)
	);
	
CREATE UNIQUE INDEX REM_INDEX ON REM_REMEDIO(REM_ID);

	
CREATE TABLE REMEDIO_CRIANCA(
	REM_ID							INT(13)			NOT NULL,
	CRI_ID							INT(13)			NOT NULL,
	CONSTRAINT REM_CRI_PK			PRIMARY KEY (REM_ID, CRI_ID),
	CONSTRAINT REM_CRI_FK			FOREIGN KEY (REM_ID) REFERENCES REM_REMEDIO (REM_ID),
	CONSTRAINT REM_CRI_FK2 			FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE UNIQUE INDEX REMEDIO_CRIANCA_INDEX ON REMEDIO_CRIANCA(REM_ID,CRI_ID);


CREATE TABLE FAM_FAMILIAR(
	FAM_ID							INT(13)			NOT NULL,
	FAM_DOENCA						VARCHAR(30)		NOT NULL,
	FAM_PARENTESCO					VARCHAR(1)		NOT NULL,
	CRI_ID							INT(13)			NOT NULL,
	CONSTRAINT FAM_PK				PRIMARY KEY (FAM_ID),
	CONSTRAINT FAM_FK 				FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE UNIQUE INDEX FAM_INDEX ON FAM_FAMILIAR(CRI_ID);

	
CREATE TABLE HABITO_URINARIO(
	HAB_URI_ID						INT(13)			NOT NULL,
	HAB_URI_FREQUENCIA_NUMERO		INT(2)			NOT NULL,
	HAB_URI_FREQUENCIA_MEDIDA		VARCHAR(30)		NOT NULL,
	HAB_URI_HEMATURIA				INT(1)			NOT NULL,
	HAB_URI_DATA					DATE			NOT NULL,
	CRI_ID							INT(13)			NOT NULL,
	CONSTRAINT HAB_URI_PK			PRIMARY KEY (HAB_URI_ID),
	CONSTRAINT HAB_URI_FK			FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE UNIQUE INDEX HAB_URI_INDEX ON HABITO_URINARIO(CRI_ID);

	
CREATE TABLE HABITO_INTESTINAL(
	HAB_INT_ID						INT(13)			NOT NULL,
	HAB_INT_FREQUENCIA_NUMERO		INT(2)			NOT NULL,
	HAB_INT_FREQUENCIA_MEDIDA		VARCHAR(30)		NOT NULL,
	HAB_INT_BRISTOL					VARCHAR(30)		NOT NULL,
	HAB_INT_MELENA					INT(1)			NOT NULL,
	HAB_INT_DATA					DATE			NOT NULL,
	CRI_ID							INT(13)			NOT NULL,
	CONSTRAINT HAB_INT_PK			PRIMARY KEY (HAB_INT_ID),
	CONSTRAINT HAB_INT_FK			FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE UNIQUE INDEX HAB_INT_INDEX ON HABITO_INTESTINAL(CRI_ID);

	
CREATE TABLE BIO_BIOQUIMICO(
	BIO_ID							INT(13)			NOT NULL,
	BIO_PROTEINAS_TOTAIS			DOUBLE(10,2)	NOT NULL,
	BIO_ALBUMINA					DOUBLE(10,2)	NOT NULL,
	BIO_PRE_ALBUMINA				DOUBLE(10,2)	NOT NULL,
	BIO_PCR							DOUBLE(10,2)	NOT NULL,
	BIO_FERRETINA					DOUBLE(10,2)	NOT NULL,
	BIO_FERRO						DOUBLE(10,2)	NOT NULL,
	BIO_ACIDO_FOLICO				DOUBLE(10,2)	NOT NULL,
	BIO_CREATININA					DOUBLE(10,2)	NOT NULL,
	BIO_CREATININA_URINA			DOUBLE(10,2)	NOT NULL,
	BIO_ACIDO_URICO					DOUBLE(10,2)	NOT NULL,
	BIO_TGO							DOUBLE(10,2)	NOT NULL,
	BIO_TGP							DOUBLE(10,2)	NOT NULL,
	BIO_DHL							DOUBLE(10,2)	NOT NULL,
	BIO_VCM							DOUBLE(10,2)	NOT NULL,
	BIO_HCM							DOUBLE(10,2)	NOT NULL,
	BIO_CHCM						DOUBLE(10,2)	NOT NULL,
	BIO_RDW							DOUBLE(10,2)	NOT NULL,
	BIO_HEMOGLOBINA					DOUBLE(10,2)	NOT NULL,
	BIO_HEMATOCRITO					DOUBLE(10,2)	NOT NULL,
	BIO_PLAQUETA					DOUBLE(10,2)	NOT NULL,
	BIO_LEUCOCITO					DOUBLE(10,2)	NOT NULL,
	BIO_LINFOCITO					DOUBLE(10,2)	NOT NULL,
	BIO_NEUTROFILO					DOUBLE(10,2)	NOT NULL,
	BIO_GLICEMIA					DOUBLE(10,2)	NOT NULL,
	BIO_INSULENIMIA					DOUBLE(10,2)	NOT NULL,
	BIO_T4_LIVRE					DOUBLE(10,2)	NOT NULL,
	BIO_CALCIO						DOUBLE(10,2)	NOT NULL,
	BIO_SODIO						DOUBLE(10,2)	NOT NULL,
	BIO_POTASSIO					DOUBLE(10,2)	NOT NULL,
	BIO_DATA						DATE			NOT NULL,
	CRI_ID							INT(13)			NOT NULL,
	CONSTRAINT BIO_PK				PRIMARY KEY (BIO_ID),
	CONSTRAINT BIO_FK				FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE UNIQUE INDEX BIO_INDEX ON BIO_BIOQUIMICO(CRI_ID);

	
CREATE TABLE HABITO_ALIMENTAR(
	HAB_ALI_ID						INT(13)		NOT NULL,
	HAB_ALI_ALIMENTO				VARCHAR(30)	NOT NULL,
	HAB_ALI_REFEICAO				VARCHAR(30)	NOT NULL,
	HAB_ALI_HORARIO					VARCHAR(30)	NOT NULL,
	HAB_ALI_FREQUENCIA				VARCHAR(30)	NOT NULL,
	HAB_ALI_FREQUENCIA_NUMERO		INT(2)		NOT NULL,
	HAB_ALI_DATA					DATE		NOT NULL,
	CRI_ID							INT(13)		NOT NULL,
	CONSTRAINT HAB_ALI_PK			PRIMARY KEY (HAB_ALI_ID),
	CONSTRAINT HAB_ALI_FK			FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE UNIQUE INDEX HAB_ALI_INDEX ON HABITO_ALIMENTAR(CRI_ID);

	
CREATE TABLE REC_RECORDATORIO(
	REC_ID							INT(13) 		NOT NULL,
	REC_ALIMENTO					VARCHAR(30)		NOT NULL,
	REC_HORARIO						VARCHAR(5)		NOT NULL,
	REC_REFEICAO					VARCHAR(30)		NOT NULL,
	REC_DATA						DATE			NOT NULL,
	CRI_ID							INT(13)			NOT NULL,
	CONSTRAINT REC_PK				PRIMARY KEY (REC_ID),
	CONSTRAINT REC_FK				FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE UNIQUE INDEX REC_INDEX ON REC_RECORDATORIO(CRI_ID);
	
CREATE TABLE ORI_ORIENTACAO(
	ORI_ID							INT(13)			NOT NULL,
	ORI_ALIMENTO					VARCHAR(30)		NOT NULL,
	ORI_REFEICAO					VARCHAR(30)		NOT NULL,
	ORI_HORARIO						VARCHAR(5)		NOT NULL,
	ORI_DATA						DATE 			NOT NULL,
	CRI_ID							INT(13)			NOT NULL,
	CONSTRAINT ORI_PD				PRIMARY KEY (ORI_ID),
	CONSTRAINT ORI_FK				FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE UNIQUE INDEX ORI_INDEX ON ORI_ORIENTACAO(CRI_ID);