CREATE TABLE CRI_CRIANCA(
	CRI_ID							NUMBER(13) 		NOT NULL,
	CRI_NOME						VARCHAR2(30) 	NOT NULL,
	CRI_PAI							VARCHAR2(30) 	NOT NULL,
	CRI_MAE							VARCHAR2(30) 	NOT NULL,
	CRI_NASCIMENTO 					DATE			NOT NULL,
	CRI_MOTIVO						VARCHAR2(30)	NOT NULL,
	CRI_TELEFONE					NUMBER(11)		NOT NULL,
	CRI_SEXO						VARCHAR2(1)		NOT NULL,
	CONSTRAINT CRI_PK 				PRIMARY KEY (CRI_ID)
	);
	
CREATE TABLE CLI_CLINICO(
	CLI_ID							NUMBER(13)		NOT NULL,
	CLI_DOENCA						VARCHAR2(30)	NOT NULL,
	CONSTRAINT CLI_PK				PRIMARY KEY (CLI_ID),
	CONSTRAINT CLI_UK				UNIQUE (CLI_DOENCA)
	);
	
CREATE TABLE CLINICO_CRIANCA(
	CRI_ID							NUMBER(13)		NOT NULL,
	CLI_ID							NUMBER(13)		NOT NULL,
	CONSTRAINT CLI_CRI_PK			PRIMARY KEY (CRI_ID, CLI_ID),
	CONSTRAINT CLI_CRI_FK			FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID),
	CONSTRAINT CLI_CRI_FK2			FOREIGN KEY (CLI_ID) REFERENCES CLI_CLINICO (CLI_ID)
	);
	
CREATE TABLE ANT_ANTROPOMETRICO(
	ANT_ID							NUMBER(13)		NOT NULL,
	ANT_PESO_HABITUAL				NUMBER(5,2)		NOT NULL,
	ANT_PESO_ATUAL					NUMBER(5,2)		NOT NULL,
	ANT_PESO_ESTIMADO				NUMBER(5,2)		NOT NULL,
	ANT_ESTATURA					NUMBER(5,2)		NOT NULL,
	ANT_PERIMETRO_CRANIANO  		NUMBER(5,2)		NOT NULL,
	ANT_PERIMETRO_TORACICO			NUMBER(5,2)		NOT NULL,
	ANT_ALTERACAO_PESO_RECENTE		NUMBER(5,2)		NOT NULL,
	ANT_CIRCUNFERENCIA_ABDOMINAL	NUMBER(5,2)		NOT NULL,
	ANT_CIRCUNFERENCIA_COXA			NUMBER(5,2)		NOT NULL,
	ANT_CIRCUNFERENCIA_PANTURRILHA	NUMBER(5,2)		NOT NULL,
	ANT_CIRCUNFERENCIA_PESCOCO		NUMBER(5,2)		NOT NULL,
	ANT_DOBRA_CUTANEA_TRICIPITAL	NUMBER(5,2)		NOT NULL,
	ANT_DOBRA_CUTANEA_SUBESCALAR	NUMBER(5,2)		NOT NULL,
	ANT_DOBRA_CUTANEA_BICIBITAL		NUMBER(5,2)		NOT NULL,
	ANT_DOBRA_CUTANEA_SUPRA_ILIACA	NUMBER(5,2)		NOT NULL,
	ANT_AREA_MUSCULAR_POLEGAR		NUMBER(5,2)		NOT NULL,
	ANT_DATA						DATE			NOT NULL,
	CRI_ID							NUMBER(13)		NOT NULL,
	CONSTRAINT ANT_PK 				PRIMARY KEY (ANT_ID),
	CONSTRAINT ANT_FK				FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE TABLE REM_REMEDIO(
	REM_ID							NUMBER(13) 		NOT NULL,
	REM_NOME						VARCHAR2(30)	NOT NULL,
	CONSTRAINT REM_PK				PRIMARY KEY (REM_ID)
	);
	
CREATE TABLE REMEDIO_CRIANCA(
	REM_ID							NUMBER(13)		NOT NULL,
	CRI_ID							NUMBER(13)		NOT NULL,
	CONSTRAINT REM_CRI_PK			PRIMARY KEY (REM_ID, CRI_ID),
	CONSTRAINT REM_CRI_FK			FOREIGN KEY (REM_ID) REFERENCES REM_REMEDIO (REM_ID),
	CONSTRAINT REM_CRI_FK2 			FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);

CREATE TABLE FAM_FAMILIAR(
	FAM_ID							NUMBER(13)		NOT NULL,
	FAM_DOENCA						VARCHAR2(30)	NOT NULL,
	FAM_PARENTESCO					VARCHAR2(1)		NOT NULL,
	CRI_ID							NUMBER(13)		NOT NULL,
	CONSTRAINT FAM_PK				PRIMARY KEY (FAM_ID),
	CONSTRAINT FAM_FK 				FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE TABLE HABITO_URINARIO(
	HAB_URI_ID						NUMBER(13)		NOT NULL,
	HAB_URI_FREQUENCIA_NUMERO		NUMBER(2)		NOT NULL,
	HAB_URI_FREQUENCIA_MEDIDA		VARCHAR2(30)	NOT NULL,
	HAB_URI_HEMATURIA				VARCHAR2(30)	NOT NULL,
	HAB_URI_DATA					DATE			NOT NULL,
	CRI_ID							NUMBER(13)		NOT NULL,
	CONSTRAINT HAB_URI_PK			PRIMARY KEY (HAB_URI_ID),
	CONSTRAINT HAB_URI_FK			FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE TABLE HABITO_INTESTINAL(
	HAB_INT_ID						NUMBER(13)		NOT NULL,
	HAB_INT_FREQUENCIA_NUMERO		NUMBER(2)		NOT NULL,
	HAB_INT_FREQUENCIA_MEDIDA		VARCHAR2(30)	NOT NULL,
	HAB_INT_BRISTOL					VARCHAR2(30)	NOT NULL,
	HAB_INT_MELENA					BOOLEAN			NOT NULL,
	HAB_INT_DATA					DATE			NOT NULL,
	CRI_ID							NUMBER(13)		NOT NULL,
	CONSTRAINT HAB_INT_PK			PRIMARY KEY (HAB_INT_ID),
	CONSTRAINT HAB_INT_FK			FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE TABLE BIO_BIOQUIMICO(
	BIO_ID							NUMBER(13)		NOT NULL,
	BIO_PROTEINAS_TOTAIS			NUMBER(10,2)	NOT NULL,
	BIO_ALBUMINA					NUMBER(10,2)	NOT NULL,
	BIO_PRE_ALBUMINA				NUMBER(10,2)	NOT NULL,
	BIO_PCR							NUMBER(10,2)	NOT NULL,
	BIO_FERRETINA					NUMBER(10,2)	NOT NULL,
	BIO_FERRO						NUMBER(10,2)	NOT NULL,
	BIO_ACIDO_FOLICO				NUMBER(10,2)	NOT NULL,
	BIO_CREATININA					NUMBER(10,2)	NOT NULL,
	BIO_CREATININA_URINA			NUMBER(10,2)	NOT NULL,
	BIO_ACIDO_URICO					NUMBER(10,2)	NOT NULL,
	BIO_TGO							NUMBER(10,2)	NOT NULL,
	BIO_TGP							NUMBER(10,2)	NOT NULL,
	BIO_DHL							NUMBER(10,2)	NOT NULL,
	BIO_VCM							NUMBER(10,2)	NOT NULL,
	BIO_HCM							NUMBER(10,2)	NOT NULL,
	BIO_CHCM						NUMBER(10,2)	NOT NULL,
	BIO_RDW							NUMBER(10,2)	NOT NULL,
	BIO_HEMOGLOBINA					NUMBER(10,2)	NOT NULL,
	BIO_HEMATOCRITO					NUMBER(10,2)	NOT NULL,
	BIO_PLAQUETA					NUMBER(10,2)	NOT NULL,
	BIO_LEUCOCITO					NUMBER(10,2)	NOT NULL,
	BIO_LINFOCITO					NUMBER(10,2)	NOT NULL,
	BIO_NEUTROFILO					NUMBER(10,2)	NOT NULL,
	BIO_GLICEMIA					NUMBER(10,2)	NOT NULL,
	BIO_INSULENIMIA					NUMBER(10,2)	NOT NULL,
	BIO_T4_LIVRE					NUMBER(10,2)	NOT NULL,
	BIO_CALCIO						NUMBER(10,2)	NOT NULL,
	BIO_SODIO						NUMBER(10,2)	NOT NULL,
	BIO_POTASSIO					NUMBER(10,2)	NOT NULL,
	BIO_DATA						DATE			NOT NULL,
	CRI_ID							NUMBER(13)		NOT NULL,
	CONSTRAINT BIO_PK				PRIMARY KEY (BIO_ID),
	CONSTRAINT BIO_FK				FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE TABLE HABITO_ALIMENTAR(
	HAB_ALI_ID						NUMBER(13)		NOT NULL,
	HAB_ALI_ALIMENTO				VARCHAR2(30)	NOT NULL,
	HAB_ALI_REFEICAO				VARCHAR2(30)	NOT NULL,
	HAB_ALI_HORARIO					VARCHAR2(30)	NOT NULL,
	HAB_ALI_FREQUENCIA				VARCHAR2(30)	NOT NULL,
	HAB_ALI_FREQUENCIA_NUMERO		NUMBER(2)		NOT NULL,
	HAB_ALI_DATA					DATE			NOT NULL,
	CRI_ID							NUMBER(13)		NOT NULL,
	CONSTRAINT HAB_ALI_PK			PRIMARY KEY (HAB_ALI_ID),
	CONSTRAINT HAB_ALI_FK			FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE TABLE REC_RECORDATORIO(
	REC_ID							NUMBER(13) 		NOT NULL,
	REC_ALIMENTO					VARCHAR2(30)	NOT NULL,
	REC_HORARIO						VARCHAR2(5)		NOT NULL,
	REC_REFEICAO					VARCHAR2(30)	NOT NULL,
	REC_DATA						DATE			NOT NULL,
	CRI_ID							NUMBER(13)		NOT NULL,
	CONSTRAINT REC_PK				PRIMARY KEY (REC_ID),
	CONSTRAINT REC_FK				FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);
	
CREATE TABLE ORI_ORIENTACAO(
	ORI_ID							NUMBER(13)		NOT NULL,
	ORI_ALIMENTO					VARCHAR2(30)	NOT NULL,
	ORI_REFEICAO					VARCHAR2(30)	NOT NULL,
	ORI_HORARIO						VARCHAR2(5)		NOT NULL,
	ORI_DATA						DATE 			NOT NULL,
	CRI_ID							NUMBER(13)		NOT NULL,
	CONSTRAINT ORI_PD				PRIMARY KEY (ORI_ID),
	CONSTRAINT ORI_FK				FOREIGN KEY (CRI_ID) REFERENCES CRI_CRIANCA (CRI_ID)
	);